package pdftext

var renameKeys = [][]string{
	[]string{"Friends-Forest", "friends", "forest"},
	[]string{"Vanguard-1099DIV", "valley forge", "1099-div"},
	[]string{"Vanguard", "www.vanguard.com"},
	[]string{"Nashoba-Analytical", "www.NashobaAnalytical.com"},
	[]string{"McHugh-Law", "mchugh law"},
	[]string{"1099-HC", "1099-hc"},
	[]string{"NRWA", "nashua", "river", "watershed", "association"},
	[]string{"NHLakes", "nh lakes"},
	[]string{"ACLU", "american civil liberties union"},
	[]string{"AdaFruit", "www.adafruit.com"},
	[]string{"ChelmsfordPC-Jim", "chelmsford primary care"},
	[]string{"CGLIC", "lincoln national"},
	[]string{"WBUR", "membership@wbur.org"},
	[]string{"Packing-List", "packing list"},
	[]string{"Rindge-Yard", "scenic", "landscaping"},
	[]string{"Rindge-Yard", "sc enic", "landscaping"},
	[]string{"Rindge-Delinq-Tax", "rindge", "delinquent"},
	[]string{"Family-Eyecare", "family eye care"},
	[]string{"Nepenthe-Foothills", "foothills property"},
	[]string{"Nepenthe-Foothills", "liverez"},
	[]string{"Groton-Insurance", "cambridge mutual", "2493319"},
	[]string{"Rindge-Insurance", "cambridge mutual", "2526086"},
	[]string{"Rindge-Insurance", "chase", "durand"},
	[]string{"Jim-LifeInsur", "administrator group"},
	[]string{"Jim-LifeInsur", "administrator", "ieee"},
	[]string{"Steward-Medical", "steward health care"},
	[]string{"Steward-Medical", "steward medical"},
	[]string{"Rindge-Water", "jaffrey", "water"},
	[]string{"Nature-Conservancy", "nature", "conservancy"},
	[]string{"Auto-Excise", "groton", "excise"},
	[]string{"Rindge-Tax", "town of rindge", "tax collector"},
	[]string{"Nepenthe-NHOA", "nhoa"},
	[]string{"Groton-Water", "groton water department"},
	[]string{"CGLIC", "whole life"},
	[]string{"Rindge-Telephone", "fairpoint"},
	[]string{"AmericanForests", "american forests"},
	[]string{"Groton-Heating", "spadafore", "oil"},
	[]string{"Groton-Heating", "wilson", "hvac"},
	[]string{"NetApp", "netapp"},
	[]string{"NVMC", "nashoba valley med"},
	[]string{"CongShalom", "congregation shalom"},
	[]string{"CongShalom", "congregationshalom.org"},
	[]string{"Delicate-Yard", "willow", "landscape"},
	[]string{"Rindge-Generator", "powers generator"},
	[]string{"Rindge-Door", "overhead door company of concord"},
	[]string{"Costco-Visa", "costco anywhere visa"},
	[]string{"Cuisinart", "cuisinart"},
	[]string{"Nepenthe-Electric", "aps", "energy", "arizona"},
	[]string{"Nepenthe-Electric", "aps.com"},
	[]string{"Sedona-Sewer-Past-Due", "Roadrunner", "past due", "Sedona"},
	[]string{"Nepenthe-Water", "arizona", "water"},
	[]string{"Sedona-Tax", "yavapai", "treasurer"},
	[]string{"Nepenthe-Tax", "yavapai", "treasurer", "nepenthe"},
	[]string{"Nepenthe-Tax-Refund", "yavapai", "treasurer", "refund"},
	[]string{"Nepenthe-Notice-Value", "yavapai", "assessor", "nepenthe"},
	[]string{"Buckboard-Notice-Value", "yavapai", "assessor", "hills"},
	[]string{"Buckboard-HOA", "western", "hills", "property", "owner"},
	[]string{"Groton-Tax", "town of groton", "real estate", "tax"},
	[]string{"Groton-Water", "grotonwater"},
	[]string{"Medical-Podiatrist", "jeffrey", "resnick"},
	[]string{"Fios", "fios"},
	[]string{"Auto-Service", "wiisonsservicegroton"},
	[]string{"Rindge-Alarm", "central", "monitoring", "service"},
	[]string{"Motion-FCU", "federal credit union"},
	[]string{"Optum-HSA", "optum bank"},
	[]string{"Loaves-Fishes", "loaves & fishes"},
	[]string{"Jim-Longterm", "columbus life"},
	[]string{"Medical-DrH", "harasimowicz"},
	[]string{"Groton-Fuel", "heating oil"},
	[]string{"Groton-Fuel", "eastern propane", "diesel"},
	[]string{"Groton-Fuel", "800", "696", "0432", "diesel"},
	[]string{"Medical-Reilly", "baptist", "hospital"},
	[]string{"Nashoba-Radiology", "nashoba radiology"},
	[]string{"Nashoba-Pathology", "nashoba", "valley", "pathology"},
	[]string{"Auto-Registration", "massachusetts vehicle registration renewal"},
	[]string{"Citizens-Bank", "citizens drive"},
	[]string{"Citizens-Bank", "citizens bank"},
	[]string{"Netapp-Stock", "netapp", "stock"},
	[]string{"BofA", "bank of america"},
	[]string{"NetApp", "network appliance"},
	[]string{"Check", "features", "exceed industry"},
	[]string{"Check", "do not write, stamp or sign below this line"},
	[]string{"Rindge-Electric", "eversource"},
	[]string{"Groton-Electric", "groton", "electric", "light"},
	[]string{"Rindge-Pest", "pest", "services", "rindge"},
	[]string{"Rindge-Pest", "pest", "services", "florence"},
	[]string{"Rindge-Pest", "pest", "management", "florence"},
	[]string{"Groton-Pest", "montachusett", "pest"},
	[]string{"Anelons-Chiro", "terry", "anelons"},
	[]string{"Rindge-Reassessment", "new assessment", "rindge"},
	[]string{"Nepenthe-Insurance", "State Farm"},
	[]string{"Buckboard-Insurance", "Shermantine"},
	[]string{"Subaru-Loan", "subaru motors finance"},
	[]string{"Epilepsy-Foundation", "Epilepsy", "Foundation"},
	[]string{"Rindge-Belletetes", "Lumber Barns"},
	[]string{"Rindge-Belletetes", "Belletetes"},
	[]string{"Nashoba-Family-Med", "nashoba family med"},
	[]string{"Mass-1099G", "1099-G", "Massachusetts"},
	[]string{"Mass-DOR-Assessment", "Intent", "Assess", "Massachusetts"},
	[]string{"Home-Depot", "More saving", "More doing"},
	[]string{"Morgan-Stanley", "morgan", "stanley"},
	[]string{"Home-Depot.com", "homedepot.com"},
	[]string{"CLAPA", "contoocook lake", "preservation"},
	[]string{"CLAPA", "contoocook lake", "assoc"},
	[]string{"Quest-Labs", "quest diagnostics"},
	[]string{"Auto-Repair", "wilsonservice"},
	[]string{"Auto-Repair", "www.wilsonsservicegroton"},
	[]string{"Dental", "peter", "breen"},
	[]string{"EFTPS", "EFTPS"},
	[]string{"Sharon-ENT", "Ear", "Nose", "Throat"},
	[]string{"Diving", "Northeast", "Scuba"},
	[]string{"Habitat-Humanity", "habitat", "humanity"},
	[]string{"Brown-Insurance", "brown", "pepperell"},
	[]string{"HPHC", "harvard pilgrim"},
	[]string{"UHC", "united", "health", "care"},
	[]string{"Audi-Nashua"},
	[]string{"Auto-Insurance", "commerce", "insurance"},
	[]string{"BIDMC-Medical", "beth", "israel", "deaconess"},
	[]string{"BIDMC-Medical", "associated", "physicians", "bidmc"},
	[]string{"Boundaries-Therapy"},
	[]string{"Boat-Insurance", "foremost", "insurance"},
	[]string{"Myette"},
	[]string{"Abby-Hall-Scholarship", "abby", "hall"},
	[]string{"ETrade", "E*trade"},
	[]string{"Village-Subaru"},
	[]string{"Nashua-Subaru"},
	[]string{"Helfman-Lasky"},
	[]string{"Medical-Lab", "Emerson", "Pathology"},
	[]string{"Audi-America", "Audi", "America"},
	[]string{"Subaru-America"},
	[]string{"Vanguard", "Vanguard", "Group"},
	[]string{"Boat-License", "boat", "renewal", "notice"},
	[]string{"Nashoba-ED", "steward", "emergency", "physicians"},
	[]string{"Rindge-Assoc", "woodmere association"},
	[]string{"Rindge-Fuel", "eastern", "propane", "rindge"},
	[]string{"Nepenthe-Gas", "unisource"},
	[]string{"CVS-Drugs", "CVS", "pharmacy"},
	[]string{"Buckboard-Sedona-Rentals", "buckboard", "sedona", "rentals"},
	[]string{"Delta-Dental", "delta", "dental"},
	[]string{"Rindge-Cable", "argent", "communications"},
	[]string{"AMEX", "american", "express"},
	[]string{"Goodwill", "goodwill", "industries"},
	[]string{"Citibank-CC", "citibank", "client", "services"},
	[]string{"Nepenthe-Telephone", "CenturyLink"},
	[]string{"Nepenthe-Telephone", "qwest"},
	[]string{"Circuit-City-Chase", "chase", "card", "services", "circuit", "city"},
	[]string{"Park-West"},
	[]string{"Rindge-Electric", "PSNH"},
	[]string{"Rindge-Construction", "LAMPS", "PLUS"},
	[]string{"Rindge-Construction", "cushnie", "moore"},
	[]string{"Rindge-Construction", "james", "libby", "moore"},
	[]string{"Rindge-Construction", "selmer", "foundations"},
	[]string{"Groton-Cable", "charter", "cable"},
	[]string{"Eastern-Propane", "eastern", "propane"},
	[]string{"Acton-Toyota", "Acton", "Toyota"},
	[]string{"Nashua-Toyota", "Nashua", "Toyota"},
	[]string{"Sharon-SIMPLE", "Vanguard", "SIMPLE", "IRA"},
	[]string{"Sharon-SIMPLE", "Fidelity", "SIMPLE", "IRA"},
	[]string{"Sharon-SIMPLE2", "smith", "barney", "SIMPLE", "IRA"},
	[]string{"Sharon-Schwartz", "sharon", "richard", "schwartz"},
	[]string{"Jim-Schwartz", "james", "richard", "schwartz"},
	[]string{"Groton-Security", "adt", "security"},
	[]string{"Rindge-Security", "monadnock", "security"},
	[]string{"Rindge-Plumbing", "dupre", "plumbing"},
	[]string{"Smith-Barney"},
	[]string{"MVJF", "Merrimack", "Jewish", "Federation"},
	[]string{"Fidelity-401K", "Fidelity", "netbenefits"},
	[]string{"CongShalom-Donation", "enriched", "by", "donation"},
	[]string{"TelDrug"},
	[]string{"Buckboard-Sewer", "Buckboard", "Sedona", "Roadrunner", "Wastewater"},
	[]string{"Nepenthe-Sewer", "Jasmine", "Sedona", "Roadrunner", "Wastewater"},
	[]string{"Nepenthe-Cable", "NPG", "CABLE"},
	[]string{"Nepenthe-Cable", "suddenlink"},
	[]string{"Reilly-ProSports", "pro", "sports", "ortho"},
	[]string{"Asbestos-Removal", "asbestos"},
	[]string{"UFund-Reid", "u.fund", "reid"},
	[]string{"UFund-Riley", "u.fund", "riley"},
	[]string{"Middlesex-Savings", "middlesex", "savings", "bank"},
	[]string{"Fidelity", "fidelity"},
	[]string{"CCL", "Citizens'", "Climate"},
	[]string{"Tesla"},
	[]string{"Consolidated-Communications"},
	[]string{"Check", "colored", "security", "background"},
	[]string{"IBM-W2", "ibm", "w-2", "earnings", "summary"},
	[]string{"IBM-W2", "business", "machines", "w-2", "wage", "tax"},
	[]string{"IBM-Overpayment", "ibm", "overpayment"},
	[]string{"NetApp-W2", "netapp", "w-2", "earnings", "summary"},
	[]string{"Clapa-Paypal", "paypal", "1099-k"},
	[]string{"CGLIC", "lincoln", "national", "life", "insurance"},
	[]string{"1095-C"},
	[]string{"Mass-Car-Title", "department", "transportation", "title"},
	[]string{"Yellowstone-Forever"},
	[]string{"Lowell-General", "lowell", "general", "hospital"},
	[]string{"Staples"},
	[]string{"WageWorks"},
	[]string{"Groton-Council-Aging", "groton", "council", "aging"},
	[]string{"AAA", "aaa", "member"},
	[]string{"IRS", "department", "treasury", "internal", "revenue"},
	[]string{"CB-CD", "citizens", "bank", "cd", "statement"},
	[]string{"Anthem-Summary", "anthem", "health", "care", "summary"},
	[]string{"Anthem-BC", "anthem", "blue", "cross"},
	[]string{"Anthem-BCBS", "anthem", "blue", "cross", "shield"},
	[]string{"Sedona-Elite", "sedona", "elite", "properties", "mgmt"},
	[]string{"Hawaiian-Airlines"},
	[]string{"National-Parks", "national", "parks", "conservation"},
	[]string{"Tesla", "S 75D"},
	[]string{"Car-Warranty", "autoassure"},
	[]string{"Check", "pay", "order"},
	[]string{"Check", "pay", "to", "check"},
	[]string{"Check", "pay", "to", "endorse"},
	[]string{"Check", "pay", "o r d e"},
	[]string{"Check", "howard", "phyllis", "snyder", "dollars"},
	[]string{"Caremark.com"},
	[]string{"Wilsons-Service", "wilson's", "service", "center"},
	[]string{"Rindge-RE-Tax", "40 florence", "real estate", "tax"},
	[]string{"PJ-Library"},
	[]string{"Mass-Gun", "massachusetts", "firearms"},
	[]string{"Charitable", "charitable", "gift"},
	[]string{"IEEE-Membership"},
	[]string{"Sedona-Landscaping", "Harbison", "sedona"},
	[]string{"Groton-Variance"},
	[]string{"Audi-Recall", "audi", "safety", "recall"},
	[]string{"IBM-401k", "ibm", "401", "account"},
	[]string{"Parker-School", "parker", "school"},
	[]string{"Northeast-Endoscopy", "northeast", "endoscopy"},
	[]string{"1099-SA", "form", "1099-sa"},
	[]string{"VVAC", "verde", "valley", "archaeology"},
	[]string{"LGH-Cardiology", "lgh", "merrimack", "cardiology"},
	[]string{"Redstone-Properties-Sedona", "redstone", "properties", "sedona"},
	[]string{"Fast-Lane"},
	[]string{"CongShalom", "87 richardson"},
	[]string{"NetApp-CIGNA", "visalia", "claim"},
	[]string{"NetApp-CIGNA", "cigna"},
	[]string{"Sedona-Buckboard", "western hills"},
	[]string{"Murphy-Insurance", "dfmurphy.com"},
	[]string{"BankofAmerica"},
	[]string{"Metlife-Dental"},
	[]string{"Sears-Warranty"},
	[]string{"Fujitsu-ScanSnap"},
	[]string{"Kidde-Firex"},
	[]string{"JPPestServices"},
	[]string{"Brown-Insurance-Electronic-Delivery"},
	[]string{"Shoulder-Stretch"},
	[]string{"Community-Chiropractic"},
	[]string{"Community-Chiropractic", "Stephen", "Jarboe"},
	[]string{"Nashoba-Valley-Medical-Center"},
	[]string{"Rite", "Aid"},
	[]string{"Unemployment", "Insurance"},
	[]string{"Indivisible-Massachusetts"},
	[]string{"CLAPA-Milfoil-Grant", "aquatic", "infestation", "grant"},
	[]string{"Kidde-Fire-Extinguisher-Recall"},
	[]string{"Boston-Sports-Shoulder-Center"},
	[]string{"Facebook-Paypal-Payment"},
	[]string{"IBM-Profit-Sharing", "IBM", "Profit", "sharing"},
	[]string{"Massachusetts-Trigger-Bump"},
	[]string{"Experian-Freeze", "experian.", "credit", "freeze"},
	[]string{"Trex", "Decking"},
	[]string{"CLAPA-Charitable-Trusts", "New", "Hampshire", "Charitable", "trusts"},
	[]string{"Littleton-Community-Farm"},
	[]string{"IBM-Salary", "HR@IBM", "salary", "statement"},
	[]string{"Check", "Lawrence", "segal", "federalcredit"},
	[]string{"Monadnock-Security", "box", "256", "new", "ipswich"},
	[]string{"Congregation-Beth-Israel"},
	[]string{"EliteWineShipping"},
	[]string{"ActonMedical-Associates"},
	[]string{"Attorney-General-Consumer"},
	[]string{"Forest-Appliance-Service"},
	[]string{"Pontoon-Legs"},
	[]string{"Overhead-Door-Company"},
	[]string{"Westford-Eye-Center", "Dwayne B. Baharozian,"},
	[]string{"NHDES", "www.des.nh.gov"},
	[]string{"Massachusetts-Dept-Revenue-Penalty"},
	[]string{"Contoocook-Milfoil"},
	[]string{"Groton-Oil", "eastern", "hudson", "sulfur"},
	[]string{"Spine-Orthopaedic-Sport", "Spine-Orthopaedic-Sport"},
	[]string{"Social-Security", "www.socialsecurity.gov/myaccount."},
	[]string{"Peterborough-Players", "www.PeterboroughPlayers.org"},
	[]string{"Swenson-Granite", "www.swensongranite.com"},
	[]string{"MassDOR-Discrepancy", "massachusetts", "revenue", "discrepancy"},
	[]string{"Charleston-Doubletree", "Church", "street", "charleston"},
	[]string{"TSA-Precheck", "known", "traveler", "number"},
	[]string{"Subaru-Class-Action", "subaru", "defective", "lawyer"},
	[]string{"Nepenthe-HOA", "Nepenthe", "news"},
	[]string{"Scenic-Landscaping", "Landscaping", "Services"},

	//
	[]string{"Tax-Deductible"},
}
